rtl/common/soc_pkg.sv
rtl/core/rv32i_alu.sv
rtl/core/rv32i_regfile.sv
rtl/core/rv32i_imm_gen.sv
rtl/core/rv32i_decoder.sv
rtl/core/rv32i_branch_unit.sv
rtl/core/rv32i_lsu.sv
rtl/core/rv32i_core.sv
rtl/memory_ip/imem_ip_wrapper.sv
rtl/memory_ip/dmem_ip_wrapper.sv
rtl/memory_ip/config_ip_wrapper.sv
rtl/periph/pwm_peripheral.sv
rtl/periph/uart_tx.sv
rtl/periph/uart_rx.sv
rtl/periph/uart_peripheral.sv
rtl/periph/spi_master.sv
rtl/periph/spi_peripheral.sv
rtl/soc/mmio_decoder.sv
rtl/soc/riscv_fan_soc.sv
rtl/soc/riscv_fan_soc_fpga_top.sv
tb/models/spi_slave_model.sv
tb/models/uart_terminal_model.sv
tb/models/virtual_fan_model.sv
tb/models_ip/intel_ram_ip_sim_models.sv
